<?php $order = $block->getOrder(); ?>
<?php $helper = $this->helper('Cybage\Storepickup\Helper\Data'); ?>
<?= $block->getAdditionalInfoHtml() ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
        <!-- Store Order Pickup time -->   
        <div class="order-details">
        <?php if($order->getShippingMethod() == "storepickup_storepickup"):?>
        <?php $pickupInterval = $helper->getPickupInterval($order)?>
            <?php if(!empty($pickupInterval)): ?>
                <p>
                    <span class="label">
                        <?= __('Your Order Pickup Time is between <b>%1</b>', $pickupInterval['from']) ?>
                        <?= __('till  <b>%1</b>', $pickupInterval['to']) ?>                       
                    </span>
                </p>
                <p>
                    <span class="label">
                        <?= __(sprintf('Store operational hours : <b>%s</b> to <b>%s</b>', $pickupInterval['open_time'], $pickupInterval['close_time'])) ?>
                    </span>
                </p>
           <?php endif; ?>
            <?php 
                $pickupstoreId = $order->getPickupstoreId();
                $storeDetails = $helper->getPickupStoreData($pickupstoreId);
            ?>
                <p>
                    <span class="label">
                        <?= __(sprintf('Pickup store : <b>%s</b>', $storeDetails['store_name'])) ?>
                    </span>
                </p>
        <?php endif;?>
        </div>
            
    <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
<script>
       require([
           'Magento_Customer/js/customer-data'
       ], function (customerData) {
           var sections = ['cart'];
           customerData.invalidate(sections);
           customerData.reload(sections, true);
       });
</script>
