<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_ecom@cybage.com.  We will send you a copy of the source file.
 *
 * @package    Cybage_Storepickup
 * @copyright  Copyright (c) 1995-2019 Cybage Software Pvt. Ltd., India
 * http://www.cybage.com/coe/e-commerce
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_ecom@cybage.com>
 */
?>
<div class="admin__page-section-item order-shipping-method">
    <div id="pickup-date">
        <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Order Pickup Date:') ?></span></strong>
        <span class="price">
            <?php echo $block->getPickupFromDate() . ' to ' . $block->getPickupToDate() ?>
        </span>     
    </div>
</div>