<?php 
/**
  * Copyright (c) 1995-2019 Cybage Software Pvt. Ltd., India 
  * http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
  */ 
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php $helper = $this->helper('Cybage\Storepickup\Helper\Data'); ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('Order Information') ?></strong>
    </div>
    <div class="block-content">
    <?php if (!$_order->getIsVirtual()): ?>
        <div class="box box-order-shipping-address">
            <?php if ($_order->getShippingMethod() == "storepickup_storepickup"): ?>
                <strong class="box-title"><span><?= /* @escapeNotVerified */ __('Store Pickup Address') ?></span></strong>
             <?php else: ?>   
                <strong class="box-title"><span><?= /* @escapeNotVerified */ __('Shipping Address') ?></span></strong>
            <?php endif; ?>
            <div class="box-content">
                <?php $storeDetails = $helper->getPickupStoreData($_order->getPickupstoreId());?>
                <address>
                    <strong><?= $storeDetails['store_name'] ?></strong><br>
                    <?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()) ?>
                </address>
            </div>
        </div>

        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
            <?php if ($_order->getShippingDescription()): ?>
                <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                 <!-- Store Order Pickup time -->   
        <div class="order-details">
        <?php if($_order->getShippingMethod() == "storepickup_storepickup"):?>
        <?php $pickupInterval = $helper->getPickupInterval($_order)?>
            <?php if(!empty($pickupInterval)): ?>
            <br/>
                <p>
                    <span class="label">
                        <?= __('Order Pickup Time : <b>%1</b>', $pickupInterval['from']) ?>
                        <?= __('To  <b>%1</b>', $pickupInterval['to']) ?>                       
                    </span>
                </p>
                <p>
                    <span class="label">
                        <?= __(sprintf('Store operational hours : <b>%s</b> to <b>%s</b>', $pickupInterval['open_time'], $pickupInterval['close_time'])) ?>
                    </span>
                </p>
           <?php endif; ?>
        <?php endif;?>
        </div>
            <?php else: ?>
                <?= /* @escapeNotVerified */ __('No shipping information available') ?>
            <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
